services: 
  bpo: 
    restart: always
    container_name: business_process_optimization
    environment: 
      - "FIWAREHOST=127.0.0.1"
      - "HOST=127.0.0.1"
      - "NETINTERFACE=eth0"
    image: docker.ramp.eu/betterfactory/business_process_optimization
    network_mode: host
version: "3"
